theme: minima
title: Help Center
author: Kim Zaidain
email: kim.zaidain@rms.com
description: > # this means to ignore newlines until "baseurl:"
  This site was created using GitHub Pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
